// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/theme-amber-warm/Dashboard.tsx": () => import("../components/mockups/theme-amber-warm/Dashboard.tsx"),
  "./components/mockups/theme-emerald/Dashboard.tsx": () => import("../components/mockups/theme-emerald/Dashboard.tsx"),
  "./components/mockups/theme-indigo-dark/Dashboard.tsx": () => import("../components/mockups/theme-indigo-dark/Dashboard.tsx")
};
